BLOCK - A (Creation & Inspection)

In [1]:
#1D-Array

import numpy as np

arr = np.arange(1, 21)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Size:", arr.size)
print("Mean:", arr.mean())

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape: (20,)
Data Type: int64
Size: 20
Mean: 10.5


In [2]:
#5 x 5 identity matrix
import numpy as np

identity = np.eye(5)

print("Identity Matrix:\n", identity)

print("Sum:", identity.sum())

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Sum: 5.0


In [3]:
#3 x 4 matrix
import numpy as np

matrix = np.zeros((3, 4))

matrix[:, 1:3] = 1

print(matrix)

[[0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]]


In [4]:
#np.linespace 0 to 2pi
import numpy as np

points = np.linspace(0, 2*np.pi, 9)

sine_values = np.sin(points)

print("Points:")
print(points)

print("\nSine Values:")
print(sine_values)

Points:
[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]

Sine Values:
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]


In [5]:
#4 x 4 matrix
import numpy as np

np.random.seed(42)

random_matrix = np.random.randint(0, 100, (4, 4))

print("Matrix:\n")
print(random_matrix)

print("\nShape:", random_matrix.shape)
print("Minimum:", random_matrix.min())
print("Maximum:", random_matrix.max())
print("Mean:", random_matrix.mean())

Matrix:

[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]

Shape: (4, 4)
Minimum: 2
Maximum: 99
Mean: 56.75


BLOCK -B (Indexing and Slicing)

In [6]:
#np.arrange using slicing
import numpy as np

a = np.arange(20)

print("Original Array:")
print(a)

print("\nFirst 5 items:")
print(a[:5])

print("\nLast 3 items:")
print(a[-3:])

print("\nItems at even positions:")
print(a[::2])

print("\nReversed Array:")
print(a[::-1])

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

First 5 items:
[0 1 2 3 4]

Last 3 items:
[17 18 19]

Items at even positions:
[ 0  2  4  6  8 10 12 14 16 18]

Reversed Array:
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [7]:
# 5 x 5 random matrix
import numpy as np

np.random.seed(42)

matrix = np.random.randint(0, 100, (5, 5))

print("Matrix:\n")
print(matrix)

print("\nFirst Row:")
print(matrix[0])

print("\nLast Column:")
print(matrix[:, -1])

print("\nCentre 3×3 Sub-matrix:")
print(matrix[1:4, 1:4])

print("\nMain Diagonal:")
print(np.diag(matrix))

Matrix:

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]

First Row:
[51 92 14 71 60]

Last Column:
[60 74 21 37 32]

Centre 3×3 Sub-matrix:
[[82 86 74]
 [99 23  2]
 [ 1 87 29]]

Main Diagonal:
[51 82 23 29 32]


In [8]:
#Replace
import numpy as np

np.random.seed(42)

matrix = np.random.randint(0, 100, (4, 4))

print("Original Matrix:\n")
print(matrix)

matrix[matrix > 50] = -1

print("\nModified Matrix:")
print(matrix)

Original Matrix:

[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]

Modified Matrix:
[[-1 -1 14 -1]
 [-1 20 -1 -1]
 [-1 -1 -1 -1]
 [23  2 21 -1]]


In [9]:
#boolean masking
import numpy as np

a = np.arange(100)

result = a[(a % 3 == 0) & (a % 5 == 0)]

print("Values divisible by both 3 and 5:")
print(result)

Values divisible by both 3 and 5:
[ 0 15 30 45 60 75 90]


In [10]:
#np.where
import numpy as np

scores = np.array([85, 32, 60, 15, 49, 90, 37])

result = np.where(scores < 40, "fail", "pass")

print("Scores:")
print(scores)

print("\nResult:")
print(result)

Scores:
[85 32 60 15 49 90 37]

Result:
['pass' 'fail' 'pass' 'fail' 'pass' 'pass' 'fail']


In [ ]:
BLOCK C - Broadcasting

In [11]:
# 4 x 3 matrix 1D array
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

arr = np.array([10, 20, 30])

result = matrix + arr

print("Original Matrix:\n")
print(matrix)

print("\nArray:")
print(arr)

print("\nResult:")
print(result)

Original Matrix:

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array:
[10 20 30]

Result:
[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


In [12]:
# 4 x 3 column vector
import numpy as np

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

column = np.array([10,20,30,40]).reshape(4,1)

result = matrix + column

print("Matrix:\n")
print(matrix)

print("\nColumn Vector:\n")
print(column)

print("\nResult:")
print(result)

Matrix:

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Column Vector:

[[10]
 [20]
 [30]
 [40]]

Result:
[[11 12 13]
 [24 25 26]
 [37 38 39]
 [50 51 52]]


In [13]:
#np.outer
import numpy as np

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

outer = a.reshape(-1, 1) * b

print("Array A:")
print(a)

print("\nArray B:")
print(b)

print("\nOuter Product:")
print(outer)


Array A:
[1 2 3]

Array B:
[4 5 6]

Outer Product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [14]:
#Standardise
import numpy as np

np.random.seed(42)

matrix = np.random.randint(1, 100, (5, 4))

print("Original Matrix:\n")
print(matrix)

# Column mean
mean = matrix.mean(axis=0)

# Column standard deviation
std = matrix.std(axis=0)

# Standardisation
standardized = (matrix - mean) / std

print("\nColumn Means:")
print(mean)

print("\nColumn Std:")
print(std)

print("\nStandardized Matrix:")
print(standardized)

Original Matrix:

[[52 93 15 72]
 [61 21 83 87]
 [75 75 88 24]
 [ 3 22 53  2]
 [88 30 38  2]]

Column Means:
[55.8 48.2 55.4 37.4]

Column Std:
[29.10257721 29.94261178 27.4415743  35.61797299]

Standardized Matrix:
[[-0.13057263  1.49619547 -1.47221874  0.97141968]
 [ 0.17867833 -0.90840439  1.0057732   1.39255538]
 [ 0.65973539  0.8950455   1.18797849 -0.37621456]
 [-1.81427231 -0.87500717 -0.08745854 -0.99388025]
 [ 1.10643122 -0.60782941 -0.63407441 -0.99388025]]


BLOCK - D (Math Operation)

In [15]:
#evenly spaced 
import numpy as np

values = np.linspace(0, 2*np.pi, 10)

sin_values = np.sin(values)
cos_values = np.cos(values)
tan_values = np.tan(values)

print("Values:")
print(values)

print("\nSin:")
print(sin_values)

print("\nCos:")
print(cos_values)

print("\nTan:")
print(tan_values)

Values:
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]

Sin:
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]

Cos:
[ 1.          0.76604444  0.17364818 -0.5        -0.93969262 -0.93969262
 -0.5         0.17364818  0.76604444  1.        ]

Tan:
[ 0.00000000e+00  8.39099631e-01  5.67128182e+00 -1.73205081e+00
 -3.63970234e-01  3.63970234e-01  1.73205081e+00 -5.67128182e+00
 -8.39099631e-01 -2.44929360e-16]


In [16]:
#find position
import numpy as np

x = np.arange(1, 13).reshape(3, 4)

print("Matrix:\n")
print(x)

position = np.unravel_index(
    x.argmax(),
    x.shape
)

print("\nMaximum Value:", x.max())
print("Position (row, col):", position)

Matrix:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Maximum Value: 12
Position (row, col): (np.int64(2), np.int64(3))


In [17]:
#standardize 1D array
import numpy as np

a = np.array([5, 10, 15, 20, 25])

mean = a.mean()
std = a.std()

standardized = (a - mean) / std

print("Original Array:")
print(a)

print("\nStandardized:")
print(standardized)

print("\nMean:")
print(standardized.mean())

print("Standard Deviation:")
print(standardized.std())

Original Array:
[ 5 10 15 20 25]

Standardized:
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Mean:
0.0
Standard Deviation:
0.9999999999999999


In [18]:
#Dot product and matrix product

#Dot product
import numpy as np

a = np.array([1, 2, 3, 4, 5])

b = np.array([6, 7, 8, 9, 10])

dot = np.dot(a, b)

print("Dot Product:", dot)

#Matrix product
import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

product = A @ B

print("Matrix Product:\n")
print(product)

Dot Product: 130
Matrix Product:

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [19]:
#np.clip()
import numpy as np

a = np.array([
    -10,
    -3,
    0,
    4,
    7,
    12,
    100
])

result = np.clip(a, 0, 10)

print("Original:")
print(a)

print("\nAfter Clip:")
print(result)

Original:
[-10  -3   0   4   7  12 100]

After Clip:
[ 0  0  0  4  7 10 10]


BLOCK - E

In [20]:
#reshape
import numpy as np

a = np.arange(24)

print("Original Array:")
print(a)

shape1 = a.reshape(2, 12)
shape2 = a.reshape(3, 8)
shape3 = a.reshape(4, 6)
shape4 = a.reshape(2, 3, 4)

print("\nShape (2,12):")
print(shape1)

print("\nShape (3,8):")
print(shape2)

print("\nShape (4,6):")
print(shape3)

print("\nShape (2,3,4):")
print(shape4)

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Shape (2,12):
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

Shape (3,8):
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

Shape (4,6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Shape (2,3,4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [21]:
#Stack 2 1-D array
import numpy as np

a = np.array([1, 2, 3, 4, 5])

b = np.array([10, 20, 30, 40, 50])

# Stack as rows
row_stack = np.vstack((a, b))

# Stack as columns
column_stack = np.column_stack((a, b))

print("Array A:")
print(a)

print("\nArray B:")
print(b)

print("\n2-Row Matrix:")
print(row_stack)

print("\n2-Column Matrix:")
print(column_stack)

Array A:
[1 2 3 4 5]

Array B:
[10 20 30 40 50]

2-Row Matrix:
[[ 1  2  3  4  5]
 [10 20 30 40 50]]

2-Column Matrix:
[[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]]


In [22]:
#Split into 4 parts
import numpy as np

a = np.arange(20)

print("Original Array:")
print(a)

parts = np.split(a, 4)

print("\nSplit Arrays:")

for i, part in enumerate(parts, start=1):
    print(f"Part {i}:", part)

result = np.concatenate((parts[0], parts[2]))

print("\nConcatenated (Part 1 + Part 3):")
print(result)

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Split Arrays:
Part 1: [0 1 2 3 4]
Part 2: [5 6 7 8 9]
Part 3: [10 11 12 13 14]
Part 4: [15 16 17 18 19]

Concatenated (Part 1 + Part 3):
[ 0  1  2  3  4 10 11 12 13 14]


In [ ]:
BLOCK F - Mini Project

In [23]:
#Mini Project

#generate fake batch
import numpy as np

np.random.seed(42)

imgs = np.random.randint(
    0,
    256,
    size=(8, 32, 32, 3),
    dtype=np.uint8
)

print("Images Generated Successfully")

Images Generated Successfully


In [24]:
#shape and dtype
print("Shape:", imgs.shape)
print("Data Type:", imgs.dtype)

Shape: (8, 32, 32, 3)
Data Type: uint8


In [25]:
#per image brightness
brightness = imgs.mean(axis=(1, 2, 3))

print("Per Image Brightness:\n")

for i, value in enumerate(brightness):
    print(f"Image {i}: {value:.2f}")

Per Image Brightness:

Image 0: 126.29
Image 1: 127.44
Image 2: 128.21
Image 3: 127.81
Image 4: 128.30
Image 5: 124.85
Image 6: 127.37
Image 7: 128.29


In [26]:
#per chanel mean
channel_mean = imgs.mean(axis=(0, 1, 2))

print("Per Channel Mean:\n")

print("Red Mean:", channel_mean[0])
print("Green Mean:", channel_mean[1])
print("Blue Mean:", channel_mean[2])

Per Channel Mean:

Red Mean: 127.8890380859375
Green Mean: 125.938232421875
Blue Mean: 128.1339111328125


In [27]:
#image into greyscale
gray = imgs.mean(axis=3)

print("Grayscale Shape:")
print(gray.shape)

Grayscale Shape:
(8, 32, 32)


In [28]:
#calculate mean and std
channel_mean = imgs.mean(
    axis=(0,1,2),
    keepdims=True
)

channel_std = imgs.std(
    axis=(0,1,2),
    keepdims=True
)

print("Mean:\n", channel_mean)

print("\nStd:\n", channel_std)

Mean:
 [[[[127.88903809 125.93823242 128.13391113]]]]

Std:
 [[[[73.54836058 74.00559419 74.05212389]]]]


In [29]:
#standerdize image
standardized = (
    imgs - channel_mean
) / channel_std

print("Standardisation Complete")

Standardisation Complete


In [30]:
#verify mean and std
check_mean = standardized.mean(
    axis=(0,1,2)
)

check_std = standardized.std(
    axis=(0,1,2)
)

print("Mean After Standardisation:")
print(check_mean)

print("\nStd After Standardisation:")
print(check_std)

Mean After Standardisation:
[ 6.23416249e-18 -2.74438675e-17  2.72744609e-17]

Std After Standardisation:
[1. 1. 1.]


In [31]:
#find brightest image index
brightest = brightness.argmax()

print("Image with Highest Brightness:")
print(brightest)

print(
    "Brightness Value:",
    brightness[brightest]
)

Image with Highest Brightness:
4
Brightness Value: 128.29622395833334
